FROM php:5.6.36-cli-stretch

RUN apt-get update && apt-get install -y subversion && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/phd-ja/source
RUN svn co http://svn.php.net/repository/phpdoc/modules/doc-ja .
