FROM php:5.6.36-fpm-stretch

RUN apt-get update && \
    apt-get install -y less locales-all subversion vim && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /opt/phd-ja/source
RUN svn co http://svn.php.net/repository/phpdoc/modules/doc-ja .

ENV LANG en_US.UTF-8
