version: 2
jobs:
  build:
    docker:
      - image: alpine
      - image: iwamot/phd-ja
    working_directory: ~/phd-ja
    steps:
      - run: |
          apk add --update curl
          curl http://127.0.0.1/phd-ja/
