#!/bin/bash
cd /opt/phd-ja/source
mkdir -p ../admin/js
svn revert -R ja && \
svn update && \
echo 'var list = [' > ../admin/js/filelist.js && \
find en -name '*.xml' | grep -v '.svn' | sort | sed -e 's/^en\(.*\)/"ja\1",/g' >> ../admin/js/filelist.js && \
echo '];' >> ../admin/js/filelist.js
